# Generated by Django 3.1.6 on 2021-03-21 09:37

import BookApp.Randoms
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_Token', models.TextField(default=BookApp.Randoms.Random_Token, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Book_UUID', models.UUIDField(default=uuid.uuid4)),
                ('Book_Name', models.CharField(max_length=50)),
                ('Book_Description', models.TextField(blank=True, max_length=300)),
                ('Book_Price', models.IntegerField(default=0)),
                ('Book_CreateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comment_Token', models.TextField(default=BookApp.Randoms.Random_Token, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Comment_Massage', models.TextField(max_length=200)),
                ('Comment_Like', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('File_UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Files_File', models.FileField(upload_to='res/')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token_Token', models.TextField(default=BookApp.Randoms.Random_Token, max_length=100, unique=True)),
                ('Token_Code', models.CharField(default=BookApp.Randoms.Random_Code, max_length=6)),
                ('Token_CreateDate', models.DateTimeField(auto_now=True)),
                ('Token_User_Email', models.EmailField(max_length=254)),
                ('Token_User_Id', models.CharField(max_length=50)),
                ('Token_User_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Token', models.TextField(default=BookApp.Randoms.Random_Token, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('User_Id', models.CharField(max_length=50, unique=True)),
                ('User_Password', models.CharField(max_length=50)),
                ('User_Email', models.EmailField(max_length=254, unique=True)),
                ('User_Credit', models.IntegerField(default=0)),
                ('User_Name', models.CharField(default=BookApp.Randoms.Random_Name, max_length=50)),
                ('User_CreateDate', models.DateTimeField(auto_now=True)),
                ('User_Comments', models.ManyToManyField(blank=True, to='BookApp.Comment')),
                ('User_Rented_Books', models.ManyToManyField(blank=True, to='BookApp.Books')),
                ('User_Saved_Books', models.ManyToManyField(blank=True, related_name='Saved_books', to='BookApp.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=20)),
                ('Category_Description', models.TextField(max_length=100)),
                ('Category_Books', models.ManyToManyField(to='BookApp.Books')),
                ('Category_Image', models.ManyToManyField(to='BookApp.Files')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='Book_Comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='BookApp.Comment'),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_Content',
            field=models.ManyToManyField(blank=True, related_name='book_content', to='BookApp.Files'),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_File',
            field=models.ManyToManyField(related_name='book_files', to='BookApp.Files'),
        ),
        migrations.AddField(
            model_name='books',
            name='Book_Preview',
            field=models.ManyToManyField(blank=True, related_name='book_preview', to='BookApp.Files'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Author_Token', models.TextField(default=BookApp.Randoms.Random_Token, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Author_Id', models.CharField(max_length=50, unique=True)),
                ('Author_Password', models.CharField(max_length=50)),
                ('Author_Email', models.EmailField(max_length=254, unique=True)),
                ('Author_Name', models.CharField(default=BookApp.Randoms.Random_Name, max_length=50)),
                ('Author_Description', models.TextField(blank=True, max_length=300)),
                ('Author_ProfileImage', models.FileField(blank=True, upload_to='image/')),
                ('Author_CreateDate', models.DateTimeField(auto_now=True)),
                ('Author_Books', models.ManyToManyField(blank=True, related_name='author_books', to='BookApp.Books')),
                ('Author_Files', models.ManyToManyField(blank=True, related_name='author_files', to='BookApp.Files')),
            ],
        ),
        migrations.CreateModel(
            name='ADS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADS_Title', models.TextField(max_length=300)),
                ('ADS_Book', models.ManyToManyField(blank=True, related_name='ads_book', to='BookApp.Books')),
                ('ADS_Image', models.ManyToManyField(related_name='ads_image', to='BookApp.Files')),
            ],
        ),
    ]
