# Generated by Django 3.1.6 on 2021-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='File_Name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
