# Generated by Django 3.1.6 on 2021-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Files_File',
            field=models.FileField(upload_to='file/'),
        ),
    ]
