# Generated by Django 3.1.6 on 2021-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_auto_20210315_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Saved_Books',
            field=models.ManyToManyField(blank=True, related_name='Saved_books', to='BookApp.Books'),
        ),
    ]
