# Generated by Django 3.1.6 on 2021-03-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_files_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Book_Cover',
            field=models.ImageField(blank=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Author_ProfileImage',
            field=models.ImageField(blank=True, upload_to='file/'),
        ),
    ]
