# Generated by Django 3.1.6 on 2021-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_auto_20210321_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Saved_Books',
            field=models.ManyToManyField(blank=True, related_name='User_Saved_Books', to='BookApp.Books'),
        ),
    ]
