# Generated by Django 3.1.6 on 2021-04-01 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_auto_20210330_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='id',
        ),
        migrations.AddField(
            model_name='ads',
            name='ADS_UUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
