# Generated by Django 3.1.6 on 2021-04-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_auto_20210401_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='ADS_Image',
        ),
        migrations.AddField(
            model_name='ads',
            name='ADS_Image',
            field=models.ImageField(default='', upload_to='file/'),
        ),
    ]
